version: "3.9"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: usersdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  user-service-1:
    restart: on-failure
    build: .
    container_name: user-service-1
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: usersdb
      REDIS_HOST: redis
    ports:
      - "8081:8080"

  user-service-2:
    restart: on-failure
    build: .
    container_name: user-service-2
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: usersdb
      REDIS_HOST: redis
    ports:
      - "8082:8080"

  user-service-3:
    restart: on-failure
    build: .
    container_name: user-service-3
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: usersdb
      REDIS_HOST: redis
    ports:
      - "8083:8080"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service-1
      - user-service-2
      - user-service-3

  adminer:
    image: adminer
    restart: always
    ports:
      - "8086:8080"
    depends_on:
      - mysql

volumes:
  mysqldata:
